### ISSUE TITLE
Error executing fluxgui

### ISSUE THREAD

**Issue by aaferrari** [and3k/and3k-sunrise#1]
Hello and3k, I installed app-misc/fluxgui from your repository but when I try to run it, the following error occurs:
```
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/fluxgui/fluxapp.py", line 7, in <module>
    import appindicator
ImportError: No module named appindicator
```
What program or module is necessary install to satisfy this dependency? I searched about this but [there are several programs](http://gpo.zugaina.org/Search?search=appindicator) with similar name and I dont know which is the correct.

**Comment by and3k** [comment]
Hi!

The appindicator python module is provided by [dev-libs/libappindicator](http://gpo.zugaina.org/dev-libs/libappindicator). Could you check if installing it fixes your problem?

Thanks!
Bela

**Comment by aaferrari** [comment]
I was trying to install the version of libappindicator that exist in Portage but did not work, then tried with the version that is in [unity-gentoo](https://github.com/shiznix/unity-gentoo) (being the only one that has USE flags for python) but this was asking me to change the desktop profile and install a lot of programs, which gives problems with dependencies and the global flags of my system generating blocks in emerge.
Seeing that I was unable to install libappindicator (and all its dependencies) then decided to investigate about it and I found the way of using fluxgui without Unity. Thus far I have not had major problems, as soon as do some tests with the program I will make a pull request with a patch.

**Comment by and3k** [comment]
Thanks, looking forward to the patch!

**Comment by aaferrari** [comment]
Hello, first I apologize for how much delay me with this but it is that I had problems applying the patch with emerge. Although in these weeks I've been busy with other things, I was also trying various ways to solve this problem but to no avail until finally discovered that the problem was something as silly as the paths shown in the .patch file.
To conclude, then I'll send a commit with the modified ebuild and the patch that I had mentioned so if you like you can close this issue.

**Comment by and3k** [comment]
That would be great! Thanks
